### ISSUE TITLE
Ubuntu 17.10, GCC7.2, error: ‘std::function’ has not been declared

### ISSUE THREAD

**Issue by ketzu** [jameslitton/coinscope#7]
Hello,
my attempts at using coinscope have been short, but I thought I should share my problems and solutions.
I used a fresh container of ubuntu 17.10, updating and installing all libraries listed in the readme file (and libssh-dev). `make` resulted in the error `error: ‘std::function’ has not been declared` which could be fixed by adding
`#include <functional>`
to connector/src/command_Handler.cpp.
Thank you and bye,
David

**Comment by jameslitton** [comment]
Thanks for the fix. Sorry I didn't get back to you sooner. I haven't been doing work on this lately and didn't have it setup to compile. I've applied the fix.
